### ISSUE TITLE
Why "~/$HOME/..." instead of "$HOME/..." line 23 of install.sh?

### ISSUE THREAD

**Issue by galletti94** [vmchale/polyglot#1]
When I installed polyglot using

`curl -sSl https://raw.githubusercontent.com/vmchale/polyglot/master/bash/install.sh | bash -s`

I was getting the error "\~/$HOME/..."  no such directory or file. Removing the "\~/" on line 23 of install.sh, I was able to install polyglot without issues. I am wondering if there is a reason the '\~' should be there given that on line 20 the mkdir command is for "$HOME/.local/share/man/man1/" (without the '\~')?

Thank you!

**Comment by vmchale** [comment]
Thanks for the bug report! I've pushed a fix :)
