### ISSUE TITLE
Add better build instructions

### ISSUE THREAD

**Issue by athas** [vmchale/polyglot#3]
The instructions in the README show how to build `poly` from the snapshot on GitHub, but not now to build with any local modifications.  From peering at the `.travis.yml`, I think the answer is to run

```
atspkg build --pkg-args '{ cross = False, parallel = True, static = True, icc = False }'
```

but there might be something I missed.

**Comment by vmchale** [comment]
I've updated them slightly, but they may be in need of further improvement! I'll have this open until I am a little more confident than the docs for this and `atspkg`.
